version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: retrorabbit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jumpsession
    volumes:
      - ./src/main/resources/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
